# Lists

# Lists: ordered, Mutable, allows, duplicate elements.


In [1]:
myList=[0]*5

In [5]:
print(myList)

[0, 0, 0, 0, 0]


In [3]:
myList2 = [1, 2, 3, 4, 5]

In [4]:
print(myList+myList2)

[0, 0, 0, 0, 0, 1, 2, 3, 4, 5]


# Sliceing

In [32]:
myList = [1, 2, 3, 6, 5, 6, 6, 8, 9]

a = myList[1:5]
print(a)
print(myList.count(6))

[2, 3, 6, 5]
3


In [7]:
print(myList[:5])

[1, 2, 3, 4, 5]


In [8]:
print(myList[2:])

[3, 4, 5, 6, 7, 8, 9]


In [9]:
print(myList[::1])

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [10]:
print(myList[::2])

[1, 3, 5, 7, 9]


# Reverse a List.

In [12]:
print(myList[::-1])

[9, 8, 7, 6, 5, 4, 3, 2, 1]


# Copying the List.

In [14]:
List_org = ["banana","cherry","apple",]
List_cpy = List_org
print(List_cpy)

['banana', 'cherry', 'apple']


In [15]:
List_org = ["banana","cherry","apple",]
List_cpy = List_org
List_cpy.append("lemon")
print(List_cpy)
print(List_org)

['banana', 'cherry', 'apple', 'lemon']
['banana', 'cherry', 'apple', 'lemon']


In [16]:
List_org = ["banana","cherry","apple",]
List_cpy = List_org.copy() # copy method
List_cpy.append("lemon")
print(List_cpy)
print(List_org)

['banana', 'cherry', 'apple', 'lemon']
['banana', 'cherry', 'apple']


In [17]:
List_org = ["banana","cherry","apple",]
List_cpy = list(List_org)
List_cpy.append("lemon")
print(List_cpy)
print(List_org)

['banana', 'cherry', 'apple', 'lemon']
['banana', 'cherry', 'apple']


In [18]:
List_org = ["banana","cherry","apple",]
List_cpy = List_org[:]
List_cpy.append("lemon")
print(List_cpy)
print(List_org)

['banana', 'cherry', 'apple', 'lemon']
['banana', 'cherry', 'apple']


In [19]:
myList = [1, 2, 3, 4, 5, 6]
b = [i*i for i in myList]
print(myList)
print(b)

[1, 2, 3, 4, 5, 6]
[1, 4, 9, 16, 25, 36]


# TUPLES 

# Tuples: ordered, immutable, allows duplicate elements

In [21]:
myTuple = ("Max", 28, "Boston")
print(myTuple)
print(type(myTuple))

('Max', 28, 'Boston')
<class 'tuple'>


In [24]:
myTuple = tuple(["Max",28, "Boston"])
print(myTuple)

('Max', 28, 'Boston')


In [26]:
item = myTuple[0]
print(item)

Max


In [27]:
item = myTuple[1]
print(item)

28


In [28]:
item = myTuple[2]
print(item)

Boston


In [29]:
for i in myTuple:
    print(i)

Max
28
Boston


In [34]:
my_Tuple = ('a', 'p', 'p', 'l', 'e')
print(my_Tuple)

('a', 'p', 'p', 'l', 'e')


In [37]:
my_Tuple = ('a', 'p', 'p', 'l', 'e')
print(my_Tuple.count('p'))
print(my_Tuple.count('l'))
print(my_Tuple.count('o'))

2
1
0


In [43]:
my_Tuple = ('a', 'p', 'p', 'l', 'e')
print(my_Tuple.index('l'))

3


In [44]:
myList = list(my_Tuple)
print(myList)

['a', 'p', 'p', 'l', 'e']


In [47]:
myTuple2 = tuple(myList)
print(myTuple2)

('a', 'p', 'p', 'l', 'e')


# Slicing with Tuple

In [50]:
a = (1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
b = a[2:5]
print(b)
print(a[:5])
print(a[2:])

(3, 4, 5)
(1, 2, 3, 4, 5)
(3, 4, 5, 6, 7, 8, 9, 10)


In [51]:
print(a[::1])

(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)


In [52]:
print(a[::2])

(1, 3, 5, 7, 9)


In [53]:
print(a[::-1])

(10, 9, 8, 7, 6, 5, 4, 3, 2, 1)


In [56]:
my_Tuple = "Max", 28, "Boston"
name, age, city = my_Tuple
print(name)
print(age)
print(city)

Max
28
Boston


In [57]:
my_Tuple = (0, 1, 2, 3, 4)

i1, *i2, i3 = my_Tuple
print(i1)
print(i3)
print(i2)

0
4
[1, 2, 3]


In [58]:
import sys
my_list = [0,1,2,"hello",True]
my_Tuple = (0,1,2,"hello",True)
print(sys.getsizeof(my_list),"bytes")
print(sys.getsizeof(my_Tuple),"bytes")

120 bytes
80 bytes


In [61]:
import timeit
print(timeit.timeit(stmt="[0,1,2,3,4,5]",number=1000000))
print(timeit.timeit(stmt="(0,1,2,3,4,5)",number=1000000))

0.15213929999936227
0.027412599999479426


# Dictionaries

# Dictionary: Key-Value pairs, Unordered, Mutable

In [62]:
mydict = {"name":"Max", "age": 28, "City": "New York"}
print(mydict)

{'name': 'Max', 'age': 28, 'City': 'New York'}


In [64]:
mydict2 = dict(name="Mary",age=27,city = "Boston")
print(mydict2)

{'name': 'Mary', 'age': 27, 'city': 'Boston'}


In [65]:
value = mydict["name"]
print(value)

Max


In [66]:
value = mydict["age"]
print(value)

28


In [68]:
value = mydict["lastName"]
print(value)

KeyError: 'lastName'

In [69]:
mydict["email"] = "max@xyz.com"
print(mydict)


{'name': 'Max', 'age': 28, 'City': 'New York', 'email': 'max@xyz.com'}


In [70]:
mydict["email"] = "coolmax@xyz.com"
print(mydict)

{'name': 'Max', 'age': 28, 'City': 'New York', 'email': 'coolmax@xyz.com'}


In [71]:
del mydict["name"]
print(mydict)

{'age': 28, 'City': 'New York', 'email': 'coolmax@xyz.com'}


In [74]:
mydict.popitem()
print(mydict)

{'City': 'New York'}


In [75]:
if "name" in mydict:
    print(mydict["lastname"])

In [77]:
try:
    print(mydict["lastname"])
except:
    print("Error")

Error


# Loops in Dictionary

In [78]:
mydict = {"name":"Max", "age": 28, "City": "New York"}
for key in mydict:
    print(key)

name
age
City


In [79]:
for key in mydict.keys():
    print(key)

name
age
City


In [80]:
for value in mydict.values():
    print(value)

Max
28
New York


In [81]:
for key, value in mydict.items():
    print(key, value)

name Max
age 28
City New York


In [82]:
mydict_cpy = mydict
print(mydict_cpy)

{'name': 'Max', 'age': 28, 'City': 'New York'}


In [83]:
mydict_cpy = mydict
mydict_cpy["email"] = "max@xyz.com"
print(mydict_cpy)
print(mydict)

{'name': 'Max', 'age': 28, 'City': 'New York', 'email': 'max@xyz.com'}
{'name': 'Max', 'age': 28, 'City': 'New York', 'email': 'max@xyz.com'}


In [85]:
mydict_cpy = mydict.copy()
mydict_cpy["email"] = "max@xyz.com"
print(mydict_cpy)
print(mydict)

{'name': 'Max', 'age': 28, 'City': 'New York', 'email': 'max@xyz.com'}
{'name': 'Max', 'age': 28, 'City': 'New York', 'email': 'max@xyz.com'}


In [86]:
mydict = {"name":"Max", "age": 28, "City": "New York"}
mydict2 = dict(name = "Mary", age=27, city="Boston")
mydict.update(mydict2)
print(mydict)

{'name': 'Mary', 'age': 27, 'City': 'New York', 'city': 'Boston'}


# Sets : unordered, mutable, no duplicates

In [24]:
myset = {1,2,3,1,2}
print(myset)

{1, 2, 3}


In [25]:
myset = set([1,2,3,1,2])
print(myset)

{1, 2, 3}


In [26]:
myset = set("Hello")
print(myset) #unordered output

{'e', 'l', 'H', 'o'}


In [27]:
myset.add(1)
myset.add(2)
myset.add(3)
print(myset)

{1, 2, 3, 'l', 'H', 'e', 'o'}


In [28]:
myset.remove("a")
print(myset)

KeyError: 'a'

In [29]:
#myset.discard(3)
#print(myset)

In [30]:
#myset.discard(4)
#print(myset)

In [31]:
#myset.clear()
#print(myset)

In [32]:
print(myset.pop())

1


In [33]:
for i in myset:
    print(i)

2
3
l
H
e
o


In [37]:
odds={1,3,5,7,9}
evens={0,2,4,6,8}
primes={2,3,5,7}

u = odds.union(evens)
print(u)

i = odds.intersection(primes)
print(i)

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}
{3, 5, 7}


In [40]:
setA = {1,2,3,4,5,6,7,8,9}
setB = {1,2,3,10,11,12}

diff = setA.difference(setB)
print(diff)

diff = setB.symmetric_difference(setA)
print(diff)

setA.symmetric_difference_update(setB)
print(setA)

{4, 5, 6, 7, 8, 9}
{4, 5, 6, 7, 8, 9, 10, 11, 12}
{4, 5, 6, 7, 8, 9, 10, 11, 12}


In [43]:
setA = {1,2,3,4,5,6}
setB = {1,2,3}
print(setA.issubset(setB))
print(setB.issubset(setA))


False
True


# STRINGS : orderd, immutable, test representation

In [44]:
my_string = "Hello World"
print(my_string)

Hello World


In [47]:
my_string = 'I\'m a programmer'
print(my_string)

I'm a programmer


In [48]:
my_string = "I'm a programmer"
print(my_string)

I'm a programmer


In [5]:
my_string = "Hello World"
char = my_string[0]
print(char)

char = my_string[1]
print(char)

char = my_string[2]
print(char)

char = my_string[3]
print(char)

H
e
l
l


In [6]:
my_string = my_string[::-1]
print(my_string)

dlroW olleH


In [10]:
greeting = "Hello"
name = "Arpit"
print(greeting+" "+name)
print(greeting,name)

Hello Arpit
Hello Arpit


In [11]:
greeting = "Hello"
for i in greeting:
    print(i)

H
e
l
l
o


In [13]:
greeting = "Hello"
if 'e' in greeting:
    print('yes')
else:
    print('no')

yes


In [15]:
input1 = "abaaa"
input2 = "ab"
if input2 in input1:
    print('yes')
else:
    print('no')

yes


In [16]:
input1 = "abaaa"
input2 = "bab"
if input2 in input1:
    print('yes')
else:
    print('no')

no


In [17]:
my_string = '     hello world  '
my_string = my_string.strip()
print(my_string)

hello world


In [18]:
print(my_string.upper())

HELLO WORLD


In [19]:
print(my_string.lower())

hello world


In [23]:
print(my_string.startswith('h'))
print(my_string.startswith('hello'))
print(my_string.startswith('world'))

True
True
False


In [25]:
print(my_string.endswith('h'))
print(my_string.endswith('world'))

False
True


In [26]:
print(my_string.find('o'))

4


In [30]:
for i in range(len(my_string)):
    if my_string[i]=='o':
        print(i)
        

4
7


In [31]:
for i in range(len(my_string)):
    if my_string[i]=='o':
        print(i)
        break

4


In [34]:
print(my_string.count('o'))
print(my_string.count('p'))

2
0


In [35]:
print(my_string.replace('world','universe'))

hello universe


In [36]:
my_string = 'How Are You Doing'
my_string = my_string.split()
print(my_string)

['How', 'Are', 'You', 'Doing']


In [37]:
my_string = 'How,Are,You,Doing'
my_string = my_string.split(",")
print(my_string)

['How', 'Are', 'You', 'Doing']


In [41]:
my_string = 'How Are You Doing'
my_string = my_string.split()
print(my_string)
new_string = ' '.join(my_string)
print(new_string)

['How', 'Are', 'You', 'Doing']
How Are You Doing


In [42]:
my_list = ['a']*6
print(my_list)

['a', 'a', 'a', 'a', 'a', 'a']


In [11]:
var = 'Tom'
my_string = "the variable is %s"% var
print(my_string)

the variable is Tom


In [12]:
my_string = f"the variable is {var}"
print(my_string)

the variable is Tom


In [16]:
var = 3.1416789
res = "the variable is {:.5f}".format(var)
print(res)

the variable is 3.14168


# Collections 

In [14]:

#COUNTER

from collections import Counter
a = "aaaaabbbbbccc"
my_counter = Counter(a)
print(my_counter)
print(len(my_counter))
print(my_counter.items())
print(my_counter.keys())
print(my_counter.values())
print(my_counter.most_common(1))
print(my_counter.most_common(2))
print(my_counter.most_common(1)[0][0])
print(list(my_counter.elements()))

Counter({'a': 5, 'b': 5, 'c': 3})
3
dict_items([('a', 5), ('b', 5), ('c', 3)])
dict_keys(['a', 'b', 'c'])
dict_values([5, 5, 3])
[('a', 5)]
[('a', 5), ('b', 5)]
a
['a', 'a', 'a', 'a', 'a', 'b', 'b', 'b', 'b', 'b', 'c', 'c', 'c']


In [31]:

# NAMEDTUPLE

from collections import namedtuple
Point = namedtuple('Point','x,y')
pt = Point(1,-4)
print(pt)
print(pt.x, pt.y)

Point(x=1, y=-4)
1 -4


In [33]:

#ORDEREDDICT

from collections import OrderedDict
ordered_dict = OrderedDict()
ordered_dict['a'] = 1
ordered_dict['b'] = 2
ordered_dict['c'] = 3
ordered_dict['d'] = 4
ordered_dict['a'] = 5
print(ordered_dict)

OrderedDict([('a', 5), ('b', 2), ('c', 3), ('d', 4)])


In [34]:
ordered_dict = {}
ordered_dict['a'] = 1
ordered_dict['b'] = 2
ordered_dict['c'] = 3
ordered_dict['d'] = 4
ordered_dict['a'] = 5
print(ordered_dict)

{'a': 5, 'b': 2, 'c': 3, 'd': 4}


In [43]:

#DEFAULTDICT

from collections import defaultdict
d = defaultdict(int)
d['a'] = 1
d['b'] = 2
print(d['a'])
print(d['b'])
print(d['c'])

1
2
0


In [54]:

#DEQUE

from collections import deque
d = deque()
d.append(1)
d.append(2)
print(d)
#.................................
d.appendleft(3)
print(d)

#.................................
d.pop()
print(d)
d.popleft()
print(d)
#.................................
d.clear()
print(d)

deque([1, 2])
deque([3, 1, 2])
deque([3, 1])
deque([1])
deque([])


In [55]:
d.append(1)
d.append(2)
d.append(3)
d.append(4)
d.append(5)
print(d)
#.................................

d.rotate(1)
print(d)
d.rotate(-1)
print(d)

deque([1, 2, 3, 4, 5])
deque([5, 1, 2, 3, 4])
deque([1, 2, 3, 4, 5])


# ITERTOOLS : Product, Permutation, Combination, Accumulate, GroupBy,                                    infinite iterators

In [3]:
from itertools import product
a = [1, 2]
b = [3, 4]
prod = product(a, b)
print(list(prod))

[(1, 3), (1, 4), (2, 3), (2, 4)]


In [11]:
from itertools import permutations
a = [1, 2, 3]
perm = permutations(a)
print(list(perm))
print("................................")
perm = permutations(a, 2)
res = list(perm)
for i in res:
    print(i)

[(1, 2, 3), (1, 3, 2), (2, 1, 3), (2, 3, 1), (3, 1, 2), (3, 2, 1)]
................................
(1, 2)
(1, 3)
(2, 1)
(2, 3)
(3, 1)
(3, 2)


In [15]:
from itertools import combinations
a = [1,2,3,4]
com = combinations(a,2)
res = list(com)
for i in res:
    print(i)

(1, 2)
(1, 3)
(1, 4)
(2, 3)
(2, 4)
(3, 4)


In [19]:
from itertools import combinations, combinations_with_replacement
a = [1,2,3,4]
com = combinations(a,2)
print(list(com))
comb_wr = combinations_with_replacement(a, 2)
print(list(comb_wr))

[(1, 2), (1, 3), (1, 4), (2, 3), (2, 4), (3, 4)]
[(1, 1), (1, 2), (1, 3), (1, 4), (2, 2), (2, 3), (2, 4), (3, 3), (3, 4), (4, 4)]


In [25]:
from itertools import accumulate
a = [1, 2, 3, 4]
acc = accumulate(a)
print(a)
print(list(acc))
print("......................................................................................")
import operator
acc = accumulate(a, func=operator.mul)
print(a)
print(list(acc))
print("......................................................................................")
a = [1,2,5,3,4]
acc = accumulate(a, func=max)
print(a)
print(list(acc))

[1, 2, 3, 4]
[1, 3, 6, 10]
......................................................................................
[1, 2, 3, 4]
[1, 2, 6, 24]
......................................................................................
[1, 2, 5, 3, 4]
[1, 2, 5, 5, 5]


In [16]:
N= int(input())
arr =[]
for i in range(N):
    arr.append(int(input()))
if len(arr)==0:
    print("-1")
elif len(arr)==1:
    print("minimum and maximum elements are same.")
else:
    mini = arr[0]
    maxi = arr[0]
    for i in range(1,len(arr)):
        if arr[i]<mini:
            mini = arr[i]
        if arr[i]>maxi:
            maxi = arr[i]
    print(mini + maxi)

10
1
2
3
4
510
1
1
2
22
32
511


In [20]:
from itertools import groupby
def smaller_than_3(x):
    return x < 3

a = [1, 2, 3, 4]
group_obj = groupby(a, key=smaller_than_3)
for key, value in group_obj:
    print(key, list(value))

True [1, 2]
False [3, 4]


In [23]:
from itertools import groupby
#def smaller_than_3(x):
 #   return x < 3

a = [1, 2, 3, 4]
group_obj = groupby(a, key=lambda x:x<3)
for key, value in group_obj:
    print(key, list(value))

True [1, 2]
False [3, 4]


#  LAMBDA argument: expression.

In [24]:
add10 = lambda x:x+10
print(add10(5))

15


In [25]:
mult = lambda x,y:x*y
print(mult(2, 7))

14


In [28]:
points2D = [(1, 2),(15, 1),(5, -1),(10,4)]
points2D_sorted = sorted(points2D, key=lambda x : x[1])
print(points2D_sorted)

points2D_sorted = sorted(points2D, key=lambda x :x[0] + x[1])
print(points2D_sorted)

[(5, -1), (15, 1), (1, 2), (10, 4)]
[(1, 2), (5, -1), (10, 4), (15, 1)]


In [30]:
a = [1,2,3,4,5]
b = map(lambda x:x*2,a)
print(list(b))
c = [x*2 for x in a]
print(c)

[2, 4, 6, 8, 10]
[2, 4, 6, 8, 10]


In [32]:
a = [1,2,3,4,5,6]
b = filter(lambda x:x%2==0,a)
print(list(b))
c = [x for x in a if x%2==0]
print(c)

[2, 4, 6]
[2, 4, 6]


#  Exceptions

In [2]:
a = [1, 2, 3]
a.remove(4)
print(a)
# ValueError

ValueError: list.remove(x): x not in list

In [3]:
a[4]
#indexError

IndexError: list index out of range

In [4]:
my_dict = {'name':'max'}
my_dict['age']
# Key Error

KeyError: 'age'

In [7]:
x = -5
if x<0:
    raise Exception('x should be positive')

Exception: x should be positive

In [9]:
x = -5
assert(x>=0), 'x is not positive'

AssertionError: x is not positive

In [12]:
try:
    a = 5 / 0
except Exception as e:
    print(e)

division by zero


In [14]:
try:
    a = 5 / 1
    b = a + '10'
except ZeroDivisionError as e:
    print(e)
except TypeError as e:
    print(e)

unsupported operand type(s) for +: 'float' and 'str'


In [15]:
try:
    a = 5 / 0
    b = a + '10'
except ZeroDivisionError as e:
    print(e)
except TypeError as e:
    print(e)

division by zero


In [19]:
try:
    a = 5 / 1
    b = a + 4
except ZeroDivisionError as e:
    print(e)
except TypeError as e:
    print(e)
else:
    print('everything is fine')
finally:
    print('cleaning up ....')

everything is fine
cleaning up ....


In [22]:
class ValueTooHighError(Exception):
    pass
def test_value(x):
    if x>100:
        raise ValueTooHighError('value is to high')
try:
    test_value(200)
except ValueTooHighError as e:
    print(e)

value is to high


# Logging

In [23]:
import logging
logging.debug('This is debug message')
logging.info('This is an info message')
logging.warning('This is a warning message')
logging.error('This is an error message')
logging.critical('This is a critical message')

ERROR:root:This is an error message
CRITICAL:root:This is a critical message


#  JASON

In [8]:
import json

person = {"name":"John","age":30,"city":"New York","hasChildren":False,"title":["engineer","programmer"]}
personJSON = json.dumps(person,indent=4,sort_keys=True)
print(personJSON)

{
    "age": 30,
    "city": "New York",
    "hasChildren": false,
    "name": "John",
    "title": [
        "engineer",
        "programmer"
    ]
}


In [9]:
person = json.loads(personJSON)
print(person)

{'age': 30, 'city': 'New York', 'hasChildren': False, 'name': 'John', 'title': ['engineer', 'programmer']}


In [13]:
import json

class User:
    def __init__(self,name,age):
        self.name = name
        self.age = age
user = User('Max',27)
def encode_user(o):
    if isinstance(o,User):
        return {'name':o.name,'age':o.age,o.__class__.__name__: True}
    else:
        raise TypeError('Object of type User is not JSON serializable')
userJSON = json.dumps(user,default=encode_user)
print(userJSON)

{"name": "Max", "age": 27, "User": true}


# RANDOM 

In [14]:
import random

a = random.random()
print(a)

0.6646015371555901


In [16]:
a = random.uniform(1, 10)
print(a)

4.985265249325611


In [44]:
a = random.randint(1, 10)
print(a)

10


In [46]:
a = random.randrange(1, 10)
print(a)

3


In [53]:
import numpy as np

a = np.random.randint(0,10)
print(a)

9


In [54]:
import numpy as np

a = np.random.randint(0,10,3)
print(a)

[4 9 8]


In [56]:
import numpy as np

a = np.random.randint(0,10,(3,4))
print(a)

[[5 5 0 6]
 [8 6 2 2]
 [0 3 8 9]]


In [60]:
import numpy as np

a = np.random.randint(0,10,(3,4))
print(a)
np.random.shuffle(a)
print(a)

[[5 5 8 2]
 [8 9 4 1]
 [0 8 0 2]]
[[0 8 0 2]
 [5 5 8 2]
 [8 9 4 1]]


# DECORATORS

In [3]:
def start_end_decorator(func):
    def wrapper():
        print('Start')
        func()
        print('End')
    return wrapper
def print_name():
    print('Alex')
print_name = start_end_decorator(print_name)
print_name()

Start
Alex
End


In [4]:
def start_end_decorator(func):
    def wrapper():
        print('Start')
        func()
        print('End')
    return wrapper
@start_end_decorator
def print_name():
    print('Alex')
#print_name = start_end_decorator(print_name)
print_name()

Start
Alex
End


# Generators 

In [6]:
def mygenerator():
    yield 1
    yield 2
    yield 3
g = mygenerator()
for i in g:
    print(i)

1
2
3


In [12]:
def mygenerator():
    yield 1
    yield 2
    yield 3
g = mygenerator()
value = next(g)
print(value)
value = next(g)
print(value)
value = next(g)
print(value)
#....................


1
2
3


In [21]:
def firstn(n):
    nums = []
    num = 0
    while num < n:
        nums.append(num)
        num += 1
    return nums
def firstn_generator(n):
    num = 0
    while num < n:
        yield num
        num += 1
print(sum(firstn(10)))
print(sum(firstn_generator(10)))

45
45


In [24]:
import sys
def firstn(n):
    nums = []
    num = 0
    while num < n:
        nums.append(num)
        num += 1
    return nums
def firstn_generator(n):
    num = 0
    while num < n:
        yield num
        num += 1
print(sys.getsizeof(firstn(1000000)))
print(sys.getsizeof(firstn_generator(1000000)))

8448728
112


In [28]:
import sys
def fib(limit):
    a, b = 0, 1
    while a < limit:
        yield a
        a, b = b, a+b
fibo = fib(30000)
print(sys.getsizeof(fibo))
for i in fibo:
    print(i)
        

112
0
1
1
2
3
5
8
13
21
34
55
89
144
233
377
610
987
1597
2584
4181
6765
10946
17711
28657
